### ISSUE TITLE
Installing Spacy fails Amazon Linux AMI release 2018.03, Python3.6 

### ISSUE THREAD

**Issue by parthibane** [explosion/spaCy#2556]
I have tried installing spacy using the pip, it failed and returns the following error 

 `gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'gcc' failed with exit status 1`

   `gcc: error: murmurhash/mrmr.cpp: No such file or directory
    gcc: fatal error: no input files
    compilation terminated.
    error: command 'gcc' failed with exit status 1`

Python headers library installed : python36-devel.x86_64

Any help really appreciated. Thank you!

## My Environment
* Operating System: Amazon Linux AMI release 2018.03
* Python Version Used: Python 3.6
* spaCy Version Used:  2.0.11

## Error Details
  `copying spacy/lexeme.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/gold.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/attrs.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/typedefs.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/tokenizer.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/vectors.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/morphology.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/vocab.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/pipeline.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/matcher.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/strings.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/parts_of_speech.pyx -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/__init__.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/typedefs.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/strings.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/symbols.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/pipeline.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/tokenizer.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/attrs.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/morphology.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/structs.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/gold.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/vocab.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/lexeme.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/parts_of_speech.pxd -> build/lib.linux-x86_64-3.6/spacy
  copying spacy/syntax/stateclass.pyx -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/transition_system.pyx -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/_beam_utils.pyx -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/_state.pyx -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/ner.pyx -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/arc_eager.pyx -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/nn_parser.pyx -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/nonproj.pyx -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/__init__.pxd -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/_state.pxd -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/arc_eager.pxd -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/transition_system.pxd -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/nn_parser.pxd -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/stateclass.pxd -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/nonproj.pxd -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/syntax/ner.pxd -> build/lib.linux-x86_64-3.6/spacy/syntax
  copying spacy/tokens/token.pyx -> build/lib.linux-x86_64-3.6/spacy/tokens
  copying spacy/tokens/_retokenize.pyx -> build/lib.linux-x86_64-3.6/spacy/tokens
  copying spacy/tokens/span.pyx -> build/lib.linux-x86_64-3.6/spacy/tokens
  copying spacy/tokens/doc.pyx -> build/lib.linux-x86_64-3.6/spacy/tokens
  copying spacy/tokens/__init__.pxd -> build/lib.linux-x86_64-3.6/spacy/tokens
  copying spacy/tokens/span.pxd -> build/lib.linux-x86_64-3.6/spacy/tokens
  copying spacy/tokens/token.pxd -> build/lib.linux-x86_64-3.6/spacy/tokens
  copying spacy/tokens/doc.pxd -> build/lib.linux-x86_64-3.6/spacy/tokens
  copying spacy/tests/tokenizer/sun.txt -> build/lib.linux-x86_64-3.6/spacy/tests/tokenizer
  running build_ext
  building 'spacy.parts_of_speech' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/spacy
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -I/tmp/pip-install-75x_edhz/spacy/include -I/home/ec2-user/rasa_nlu_36/include -I/usr/include/python3.6m -c spacy/parts_of_speech.cpp -o build/temp.linux-x86_64-3.6/spacy/parts_of_speech.o -O2 -Wno-strict-prototypes -Wno-unused-function
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for spacy
  Running setup.py clean for spacy
  Running setup.py bdist_wheel for murmurhash ... error
  Complete output from command /home/ec2-user/rasa_nlu_36/bin/python36 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-75x_edhz/murmurhash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-bil_w8dn --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/murmurhash
  copying murmurhash/about.py -> build/lib.linux-x86_64-3.6/murmurhash
  copying murmurhash/__init__.py -> build/lib.linux-x86_64-3.6/murmurhash
  creating build/lib.linux-x86_64-3.6/murmurhash/tests
  copying murmurhash/tests/test_import.py -> build/lib.linux-x86_64-3.6/murmurhash/tests
  copying murmurhash/tests/__init__.py -> build/lib.linux-x86_64-3.6/murmurhash/tests
  copying murmurhash/mrmr.pyx -> build/lib.linux-x86_64-3.6/murmurhash
  copying murmurhash/__init__.pxd -> build/lib.linux-x86_64-3.6/murmurhash
  copying murmurhash/mrmr.pxd -> build/lib.linux-x86_64-3.6/murmurhash
  creating build/lib.linux-x86_64-3.6/murmurhash/include
  creating build/lib.linux-x86_64-3.6/murmurhash/include/murmurhash
  copying murmurhash/include/murmurhash/MurmurHash2.h -> build/lib.linux-x86_64-3.6/murmurhash/include/murmurhash
  copying murmurhash/include/murmurhash/MurmurHash3.h -> build/lib.linux-x86_64-3.6/murmurhash/include/murmurhash
  running build_ext
  building 'murmurhash.mrmr' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/murmurhash
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -I/tmp/pip-install-75x_edhz/murmurhash/murmurhash/include -I/home/ec2-user/rasa_nlu_36/include -I/usr/include/python3.6m -c murmurhash/mrmr.cpp -o build/temp.linux-x86_64-3.6/murmurhash/mrmr.o -O3 -Wno-strict-prototypes -Wno-unused-function
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for murmurhash
  Running setup.py clean for murmurhash
  Running setup.py bdist_wheel for cymem ... error
  Complete output from command /home/ec2-user/rasa_nlu_36/bin/python36 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-75x_edhz/cymem/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-9kuiiinz --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/cymem
  copying cymem/about.py -> build/lib.linux-x86_64-3.6/cymem
  copying cymem/__init__.py -> build/lib.linux-x86_64-3.6/cymem
  package init file 'cymem/tests/__init__.py' not found (or not a regular file)
  creating build/lib.linux-x86_64-3.6/cymem/tests
  copying cymem/tests/test_import.py -> build/lib.linux-x86_64-3.6/cymem/tests
  copying cymem/cymem.pyx -> build/lib.linux-x86_64-3.6/cymem
  copying cymem/cymem.pxd -> build/lib.linux-x86_64-3.6/cymem
  copying cymem/__init__.pxd -> build/lib.linux-x86_64-3.6/cymem
  running build_ext
  building 'cymem.cymem' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/cymem
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -I/home/ec2-user/rasa_nlu_36/include -I/usr/include/python3.6m -c cymem/cymem.cpp -o build/temp.linux-x86_64-3.6/cymem/cymem.o -O3 -Wno-strict-prototypes -Wno-unused-function
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cymem
  Running setup.py clean for cymem
  Running setup.py bdist_wheel for preshed ... error
  Complete output from command /home/ec2-user/rasa_nlu_36/bin/python36 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-75x_edhz/preshed/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-y58gfl39 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/preshed
  copying preshed/about.py -> build/lib.linux-x86_64-3.6/preshed
  copying preshed/__init__.py -> build/lib.linux-x86_64-3.6/preshed
  creating build/lib.linux-x86_64-3.6/preshed/tests
  copying preshed/tests/test_hashing.py -> build/lib.linux-x86_64-3.6/preshed/tests
  copying preshed/tests/test_pop.py -> build/lib.linux-x86_64-3.6/preshed/tests
  copying preshed/tests/test_counter.py -> build/lib.linux-x86_64-3.6/preshed/tests
  copying preshed/tests/__init__.py -> build/lib.linux-x86_64-3.6/preshed/tests
  copying preshed/maps.pyx -> build/lib.linux-x86_64-3.6/preshed
  copying preshed/counter.pyx -> build/lib.linux-x86_64-3.6/preshed
  copying preshed/__init__.pxd -> build/lib.linux-x86_64-3.6/preshed
  copying preshed/maps.pxd -> build/lib.linux-x86_64-3.6/preshed
  copying preshed/counter.pxd -> build/lib.linux-x86_64-3.6/preshed
 ` running build_ext
  building 'preshed.maps' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/preshed
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -I/tmp/pip-install-75x_edhz/preshed/include -I/home/ec2-user/rasa_nlu_36/include -I/usr/include/python3.6m -c preshed/maps.cpp -o build/temp.linux-x86_64-3.6/preshed/maps.o -O3 -Wno-strict-prototypes -Wno-unused-function
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'gcc' failed with exit status 1`
  
  ----------------------------------------
  Failed building wheel for preshed
  Running setup.py clean for preshed
  Running setup.py bdist_wheel for thinc ... error
  Complete output from command /home/ec2-user/rasa_nlu_36/bin/python36 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-75x_edhz/thinc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-tnvhr054 --python-tag cp36:
  Warning: The nvcc binary could not be located in your $PATH. For GPU capability, either add it to your path, or set $CUDA_HOME
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/thinc
  copying thinc/v2v.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/exceptions.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/i2v.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/t2v.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/describe.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/about.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/api.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/check.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/t2t.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/misc.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/__init__.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/loss.py -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/compat.py -> build/lib.linux-x86_64-3.6/thinc
  creating build/lib.linux-x86_64-3.6/thinc/tests
  copying thinc/tests/test_util.py -> build/lib.linux-x86_64-3.6/thinc/tests
  copying thinc/tests/util.py -> build/lib.linux-x86_64-3.6/thinc/tests
  copying thinc/tests/strategies.py -> build/lib.linux-x86_64-3.6/thinc/tests
  copying thinc/tests/conftest.py -> build/lib.linux-x86_64-3.6/thinc/tests
  copying thinc/tests/__init__.py -> build/lib.linux-x86_64-3.6/thinc/tests
  copying thinc/tests/test_api_funcs.py -> build/lib.linux-x86_64-3.6/thinc/tests
  creating build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_about.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_check_exceptions.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_pooling.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_difference.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_ops.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_model.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_affine.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_beam_search.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_loss.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_mem.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_rnn.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_hash_embed.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/__init__.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  copying thinc/tests/unit/test_imports.py -> build/lib.linux-x86_64-3.6/thinc/tests/unit
  creating build/lib.linux-x86_64-3.6/thinc/tests/integration
  copying thinc/tests/integration/test_mnist.py -> build/lib.linux-x86_64-3.6/thinc/tests/integration
  copying thinc/tests/integration/test_affine_learns.py -> build/lib.linux-x86_64-3.6/thinc/tests/integration
  copying thinc/tests/integration/test_roundtrip_bytes.py -> build/lib.linux-x86_64-3.6/thinc/tests/integration
  copying thinc/tests/integration/test_feed_forward.py -> build/lib.linux-x86_64-3.6/thinc/tests/integration
  copying thinc/tests/integration/__init__.py -> build/lib.linux-x86_64-3.6/thinc/tests/integration
  copying thinc/tests/integration/test_batch_norm.py -> build/lib.linux-x86_64-3.6/thinc/tests/integration
  copying thinc/tests/integration/test_shape_check.py -> build/lib.linux-x86_64-3.6/thinc/tests/integration
  copying thinc/tests/integration/test_basic_tagger.py -> build/lib.linux-x86_64-3.6/thinc/tests/integration
  creating build/lib.linux-x86_64-3.6/thinc/tests/linear
  copying thinc/tests/linear/test_avgtron.py -> build/lib.linux-x86_64-3.6/thinc/tests/linear
  copying thinc/tests/linear/test_sparse_array.py -> build/lib.linux-x86_64-3.6/thinc/tests/linear
  copying thinc/tests/linear/test_linear.py -> build/lib.linux-x86_64-3.6/thinc/tests/linear
  copying thinc/tests/linear/__init__.py -> build/lib.linux-x86_64-3.6/thinc/tests/linear
  creating build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/__init__.py -> build/lib.linux-x86_64-3.6/thinc/linear
  creating build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/_lsuv.py -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/vecs2vecs.py -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/mem.py -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/util.py -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/train.py -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/pooling.py -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/__init__.py -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/vecs2vec.py -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/vec2vec.py -> build/lib.linux-x86_64-3.6/thinc/neural
  creating build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/wrappers.py -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/load_nlp.py -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/__init__.py -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/hpbff.py -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/datasets.py -> build/lib.linux-x86_64-3.6/thinc/extra
  creating build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/convolution.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/rnn.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/lstm.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/selu.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/hash_embed.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/layernorm.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/resnet.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/embed.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/relu.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/batchnorm.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/static_vectors.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/feed_forward.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/elu.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/difference.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/model.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/affine.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/__init__.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/attention.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/maxout.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  copying thinc/neural/_classes/softmax.py -> build/lib.linux-x86_64-3.6/thinc/neural/_classes
  creating build/lib.linux-x86_64-3.6/thinc/extra/_vendorized
  copying thinc/extra/_vendorized/keras_generic_utils.py -> build/lib.linux-x86_64-3.6/thinc/extra/_vendorized
  copying thinc/extra/_vendorized/keras_datasets.py -> build/lib.linux-x86_64-3.6/thinc/extra/_vendorized
  copying thinc/extra/_vendorized/__init__.py -> build/lib.linux-x86_64-3.6/thinc/extra/_vendorized
  copying thinc/extra/_vendorized/keras_data_utils.py -> build/lib.linux-x86_64-3.6/thinc/extra/_vendorized
  copying thinc/typedefs.pyx -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/structs.pyx -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/linalg.pyx -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/__init__.pxd -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/typedefs.pxd -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/linalg.pxd -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/structs.pxd -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/compile_time_constants.pxi -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/typedefs.cpp -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/linalg.cpp -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/structs.cpp -> build/lib.linux-x86_64-3.6/thinc
  copying thinc/linear/features.pyx -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/avgtron.pyx -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/sparse.pyx -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/linear.pyx -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/serialize.pyx -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/serialize.pxd -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/__init__.pxd -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/avgtron.pxd -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/features.pxd -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/sparse.pxd -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/sparse.cpp -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/features.cpp -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/avgtron.cpp -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/linear.cpp -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/linear/serialize.cpp -> build/lib.linux-x86_64-3.6/thinc/linear
  copying thinc/neural/_funcs.pyx -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/gpu_ops.pyx -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/optimizers.pyx -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/ops.pyx -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/__init__.pxd -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/ops.pxd -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/_funcs.pxd -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/_funcs.cpp -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/gpu_ops.cpp -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/optimizers.cpp -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/neural/ops.cpp -> build/lib.linux-x86_64-3.6/thinc/neural
  copying thinc/extra/eg.pyx -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/search.pyx -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/cache.pyx -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/mb.pyx -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/eg.pxd -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/__init__.pxd -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/mb.pxd -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/search.pxd -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/cache.pxd -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/search.cpp -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/cache.cpp -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/eg.cpp -> build/lib.linux-x86_64-3.6/thinc/extra
  copying thinc/extra/mb.cpp -> build/lib.linux-x86_64-3.6/thinc/extra
  running build_ext
  `building 'thinc.linalg' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/thinc
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -I/tmp/pip-install-75x_edhz/thinc/include -I/home/ec2-user/rasa_nlu_36/include -I/usr/include/python3.6m -c thinc/linalg.cpp -o build/temp.linux-x86_64-3.6/thinc/linalg.o -O3 -Wno-strict-prototypes -Wno-unused-function
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'gcc' failed with exit status 1`
  
  ----------------------------------------
  `Failed building wheel for thinc
  Running setup.py clean for thinc
Failed to build spacy murmurhash cymem preshed thinc
Installing collected packages: murmurhash, cymem, preshed, wrapt, toolz, cytoolz, plac, dill, termcolor, msgpack-python, msgpack-numpy, thinc, ujson, regex, spacy
  Running setup.py install for murmurhash ... error
    Complete output from command /home/ec2-user/rasa_nlu_36/bin/python36 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-75x_edhz/murmurhash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1w77450l/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/rasa_nlu_36/include/site/python3.6/murmurhash:
    running install
    running build
    running build_py
    running build_ext
    building 'murmurhash.mrmr' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -I/tmp/pip-install-75x_edhz/murmurhash/murmurhash/include -I/home/ec2-user/rasa_nlu_36/include -I/usr/include/python3.6m -c murmurhash/mrmr.cpp -o build/temp.linux-x86_64-3.6/murmurhash/mrmr.o -O3 -Wno-strict-prototypes -Wno-unused-function
    gcc: error: murmurhash/mrmr.cpp: No such file or directory
    gcc: fatal error: no input files
    compilation terminated.
    error: command 'gcc' failed with exit status 1` 
    
    ----------------------------------------
`Command "/home/ec2-user/rasa_nlu_36/bin/python36 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-75x_edhz/murmurhash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1w77450l/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/rasa_nlu_36/include/site/python3.6/murmurhash" failed with error code 1 in /tmp/pip-install-75x_edhz/murmurhash`

**Comment by parthibane** [comment]
Finally found the root cause! gcc cannot find cc1plus and fixed with help of below link. https://stackoverflow.com/questions/36353302/gcc-cannot-find-cc1plus

**Comment by romanovzky** [comment]
Someone print this and send it to AWS linux team. They seem to not follow any standard convention for library and header locations and links... (not even mentioning overriding global env variables that no one uses and breaks a lot of stuff)

**Comment by iamyihwa** [comment]
I had same error, and have followed this instruction and did 
`sudo ln -s /usr/libexec/gcc/x86_64-redhat-linux/4.4.4/cc1plus /usr/local/bin/`
however I still get the same error as before. 

```  creating build/temp.linux-x86_64-3.6/thinc
  gcc -pthread -B /home/ec2-user/anaconda3/envs/allennlp/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/envs/allennlp/include/python3.6m -I/tmp/pip-install-d79yte2u/thinc/include -I/home/ec2-user/anaconda3/envs/allennlp/include/python3.6m -c thinc/linalg.cpp -o build/temp.linux-x86_64-3.6/thinc/linalg.o -O3 -Wno-strict-prototypes -Wno-unused-function
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for thinc
  Running setup.py clean for thinc
Failed to build spacy murmurhash cymem preshed thinc
Installing collected packages: murmurhash, cymem, preshed, msgpack, msgpack-numpy, toolz, cytoolz, wrapt, plac, dill, thinc, ujson, regex, spacy
  Running setup.py install for murmurhash ... error
    Complete output from command /home/ec2-user/anaconda3/envs/allennlp/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-d79yte2u/murmurhash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1he9pgzd/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'murmurhash.mrmr' extension
    gcc -pthread -B /home/ec2-user/anaconda3/envs/allennlp/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/envs/allennlp/include/python3.6m -I/tmp/pip-install-d79yte2u/murmurhash/murmurhash/include -I/home/ec2-user/anaconda3/envs/allennlp/include/python3.6m -c murmurhash/mrmr.cpp -o build/temp.linux-x86_64-3.6/murmurhash/mrmr.o -O3 -Wno-strict-prototypes -Wno-unused-function
    gcc: error: murmurhash/mrmr.cpp: No such file or directory
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/ec2-user/anaconda3/envs/allennlp/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-d79yte2u/murmurhash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1he9pgzd/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-d79yte2u/murmurhash/```

**Comment by pslacerda** [comment]
I had the same problem, it was because I didn't have `g++` installed (`gcc-c++' on Fedora).
