### ISSUE TITLE
French token_match not read correctly from disk ?

### ISSUE THREAD

**Issue by svlandeg** [explosion/spaCy#3011]
## How to reproduce the behaviour
The string **entr'amis** should match in `TOKEN_MATCH` according to the regular expression defined in [fr/tokenizer_exceptions.py](https://github.com/explosion/spaCy/blob/master/spacy/lang/fr/tokenizer_exceptions.py#L143). This is also checked by a [unit test](https://github.com/explosion/spaCy/blob/master/spacy/tests/lang/fr/test_exceptions.py#L13). However I noticed that when the tokenizer is serialized to and back from bytes, this expression does not match anymore.

To reproduce in [tokenizer.pyx](https://github.com/explosion/spaCy/blob/master/spacy/tokenizer.pyx#L409):

```
if 'token_match' in data:
             print("controle C1 (from bytes)", self.token_match("entr'amis"), self.token_match)
             self.token_match = re.compile(data['token_match']).search
             print("controle C2 (from bytes)", self.token_match("entr'amis"), self.token_match)
```
The print-out shows that the original token_match field was matching our string, but the new, read version doesn't:

> ('controle C1 (from bytes)', <regex.Match object; span=(0, 9), match="entr'amis">, <built-in method match of _regex.Pattern object at 0x000000000B50C180>)
> ('controle C2 (from bytes)', None, <built-in method search of _regex.Pattern object at 0x000000001FA0A2D0>)

This causes downstream problems: a sentence with the word "entr'amis" in it will be tokenized by splitting up "entr" and "amis" into two words:

```
french_sentence = "je suis entr'amis"
nlp = spacy.load('fr_core_news_sm')
doc = nlp(french_sentence)
for token in doc:
        print("TOKEN", token.text, token.lemma_, token.pos_, token.tag_)
```
>TOKEN je il PRON PRON__Number=Sing|Person=1
>TOKEN suis être AUX AUX__Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin
>TOKEN entr' entr' ADJ ADJ__Gender=Masc|Number=Plur
>TOKEN amis ami NOUN NOUN__Gender=Masc|Number=Plur

 When I disable reading the `self.token_match` in the method `from_bytes` (in the code above), this is fixed:
> TOKEN je il PRON PRON__Number=Sing|Person=1
> TOKEN suis être AUX AUX__Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin
> TOKEN entr'amis entr'amis VERB VERB__Gender=Masc|Tense=Past|VerbForm=Part

This problem occurs for at least all tokens that should be caught by the French regular expressions, which may explain the need for the additional large list of exceptions. The cases in the [exception list](https://github.com/explosion/spaCy/blob/master/spacy/lang/fr/_tokenizer_exceptions_list.py) are dealt with correctly in the tokenizer.

I'd be happy to look into this further but wanted to hear your feedback on desired behaviour first!

## Your Environment
* **spaCy version:** 2.0.18
* **Platform:** Windows-7-6.1.7601-SP1
* **Python version:** 3.6.7
* **Models:** en_core_web_md, en_core_web_sm, fr_core_news_md, fr_core_news_sm

**Comment by svlandeg** [comment]
It looks like the other regular expressions are OK - the issue is with the **entr'ABC** pattern that was fixed in [PR 2980](https://github.com/explosion/spaCy/pull/2980) last week.

But now I wonder why these regexp's are first compiled on the fly, and then still read from disk ?

**Comment by svlandeg** [comment]
I saw that too Matt, and I think you're right that it should be `.match`, but in this case it probably doesn't matter much because the regular expressions are all enclosed in `^` and `$` (at least the french ones).

The way that I see it now is that this isn't a bug of the serialization, because the model is never written to file (what I thought happened first). The tokenizer exceptions are all compiled during run-time, the token_match works for **entr'amis** because that bug was fixed in PR 2980, but then the old version of the model is loaded from disk in the `from_bytes` method.

**Comment by honnibal** [comment]
Hmm! Okay so, is the problem fixed (by 2980), or is there still a problem here?

**Comment by svlandeg** [comment]
The original bug is fixed in 2980, but it's not showing up in the "downstream" code I cited because the (now correctly) compiled expressions are overwritten by the (still wrong) pre-compiled version from disk.

I guess I just don't understand why the tokenizer expressions are first compiled at run-time, and then read from disk and overwritten. Either of the two would be sufficient, no?
 - If the regexps should always be read from file, the installed models should be updated when the code was updated
 - If the regexps are always compiled at run-time, they should not get overwritten by potentially older versions from file

So really I'm trying to understand whether this is a feature or a bug ;-)
