### ISSUE TITLE
Cannot train language model after upgrade to spaCy 2.1.4

### ISSUE THREAD

**Issue by PeterGilles** [explosion/spaCy#3847]
## How to reproduce the behaviour
After upgrading to spacy 2.1.4 it seems that I have to train my language model again. Training data comes from a (rudimentary, but valid) conll-file, 
```
1	Dat	-	P	_	_	0	root	_	-
2	neit	-	ADJ	_	_	0	root	_	-
3	ënnescht	-	ADJ	_	_	0	root	_	-
4	Schlass	-	N	_	_	0	root	_	-
5	gouf	-	AUX	_	_	0	root	_	-
6	tëscht	-	APPR	_	_	0	root	_	-
7	1638	-	NUM	_	_	0	root	_	-
8	–	-	$	_	_	0	root	_	-
9	'39	-	NUM	_	_	0	root	_	-
10	gebaut	-	V	_	_	0	root	_	-
11	.	-	$	_	_	0	root	_	-
```
which is converted to json with `python3 -m spacy convert POS4.conll . -t json -c conll -n 10`

Extract of the resulting json file:
 ```  {
    "id":19,
    "paragraphs":[
      {
        "sentences":[
          {
            "tokens":[
              {
                "id":0,
                "orth":"Dat",
                "tag":"P",
                "head":0,
                "dep":"ROOT"
              },
              {
                "id":1,
                "orth":"neit",
                "tag":"ADJ",
                "head":0,
                "dep":"ROOT"
              },
              {
                "id":2,
                "orth":"\u00ebnnescht",
                "tag":"ADJ",
                "head":0,
                "dep":"ROOT"
              },
              {
                "id":3,
                "orth":"Schlass",
                "tag":"N",
                "head":0,
                "dep":"ROOT"
              },
              {
                "id":4,
                "orth":"gouf",
                "tag":"AUX",
                "head":0,
                "dep":"ROOT"
              },
              {
                "id":5,
                "orth":"t\u00ebscht",
                "tag":"APPR",
                "head":0,
                "dep":"ROOT"
              },
              {
                "id":6,
                "orth":"1638",
                "tag":"NUM",
                "head":0,
                "dep":"ROOT"
              },
              {
                "id":7,
                "orth":"\u2013",
                "tag":"$",
                "head":0,
                "dep":"ROOT"
              },
              {
                "id":8,
                "orth":"'39",
                "tag":"NUM",
                "head":0,
                "dep":"ROOT"
              },
              {
                "id":9,
                "orth":"gebaut",
                "tag":"V",
                "head":0,
                "dep":"ROOT"
              },
              {
                "id":10,
                "orth":".",
                "tag":"$",
                "head":0,
                "dep":"ROOT"
              }
            ]
          },
(...)
```
However, when I then train a model with `python3 -m spacy train lb model2 POS4.json rtl_radio.jsonl` I will get this error:
```
Training pipeline: ['tagger', 'parser', 'ner']
Starting with blank model 'lb'
Counting training words (limit=0)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/cli/train.py", line 205, in train
    corpus = GoldCorpus(train_path, dev_path, limit=n_examples)
  File "gold.pyx", line 113, in spacy.gold.GoldCorpus.__init__
  File "gold.pyx", line 125, in spacy.gold.GoldCorpus.write_msgpack
KeyError: 1
```
 Checking with `python3 -m spacy debug-data lb POS4.json rtl_radio.jsonl --pipeline tagger --verbose` throws the following error: 
```
=========================== Data format validation ===========================
✔ Loaded POS4.json
✔ Loaded rtl_radio.jsonl
✔ Training data JSON format is valid
✔ Development data JSON format is valid
⠸ Analyzing corpus...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/__main__.py", line 35, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/cli/debug_data.py", line 94, in debug_data
    corpus = GoldCorpus(train_data, dev_data)
  File "gold.pyx", line 113, in spacy.gold.GoldCorpus.__init__
  File "gold.pyx", line 123, in spacy.gold.GoldCorpus.write_msgpack
  File "gold.pyx", line 277, in read_json_object
  File "gold.pyx", line 289, in json_to_tuple
KeyError: 'paragraphs'
```
I did exactly the same when using a previous version of spacy and didn't run into this problem.

## Your Environment

* Operating System: OS X
* Python Version Used: 3.6
* spaCy Version Used: 2.1.4
* Environment Information:

**Comment by ines** [comment]
This looks like the error in #3523, which happened due to a bad default – but that should be fixed in v2.1.4.

One thing I noticed in your commands: You're saving your training data as `json`, but a file you're loading in is called `rtl_radio.jsonl`. Is that a typo?

**Comment by PeterGilles** [comment]
No, this is file with the development data, in `jsonl` format. Could that create the problem? It used to work with this format in previous spacy versions.

**Comment by PeterGilles** [comment]
I tried it with loading the same file as `json`. The same error remains.

**Comment by PeterGilles** [comment]
I think I found the error, indeed something was wrong in my development data file... However, although the model seems to be trained and saved, I am getting an error:
```
✔ Saved model to output directory                                                 
lb_model/model-final

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/cli/train.py", line 271, in train
    nlp_loaded = util.load_model_from_path(epoch_model_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/util.py", line 159, in load_model_from_path
    meta = get_model_meta(model_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spacy/util.py", line 208, in get_model_meta
    raise ValueError(Errors.E054.format(setting=setting))
ValueError: [E054] No valid 'lang' setting found in model meta.json.
```
After inserting the language code `lb` into `meta.json`, I can load the model though. It seems that my newly created language class `lb` is not found during the training.

**Comment by ines** [comment]
Glad you found the problem!

> It seems that my newly created language class `lb` is not found during the training.

How did you implement the language class? Did you just edit the source and then built spaCy from source?

And what do your training logs say about creating a blank model etc.? If the `lb` language can't be found, `util.get_lang_class` should have failed, too, and the training likely wouldn't have started 🤔 But the training script also explicitly sets `meta["lang"] = nlp.lang`, so this should have definitely set the meta language to `lb`...

**Comment by PeterGilles** [comment]
To create the `lb` language class I simply created a corresponding folder in the `lang` folder and developed some rules for tokenisation and lemmatisation (see https://github.com/PeterGilles/spaCy/tree/master/spacy/lang/lb). 

The training as such looked like this. Note that `lb` is instantiated then as a blank model.

```
python3 -m spacy train lb lb_model lux_POS_training.json lux_POS_development.json 
⚠ Output directory is not empty
This can lead to unintended side effects when saving the model. Please use an
empty directory or a different path instead. If the specified output path
doesn't exist, the directory will be created for you.
Training pipeline: ['tagger', 'parser', 'ner']
Starting with blank model 'lb'
Counting training words (limit=0)

Itn    Dep Loss    NER Loss      UAS    NER P    NER R    NER F    Tag %  Token %  CPU WPS  GPU WPS
---  ----------  ----------  -------  -------  -------  -------  -------  -------  -------  -------
✔ Saved model to output directory                                                 
lb_model/model-final
```

**Comment by honnibal** [comment]
@PeterGilles Could you try again with v2.2? The new `spacy debug-data` command should be especially helpful.
