### ISSUE TITLE
Error exporting html output from displacy render

### ISSUE THREAD

**Issue by mansiganatra** [explosion/spaCy#3926]
Hi,
I'm trying to render the output from displacy ent in the jupyter notebook and also save the html form to the disk. I have the following code:

```
    displacy.render(document, style='ent', jupyter=True)
    html =  displacy.render(document, style='ent', page=True)
    print("HTML markup: ", html)
    with open("./1.html", 'w+', encoding="utf-8") as fp:
        fp.write(html)
        fp.close()
``` 
But this doesn't work for exporting the html. On looking through the code in _init_.py I found that it is due to the following lines of code:
```
    _html["parsed"] = renderer.render(parsed, page=page, minify=minify).strip()
    html = _html["parsed"]
    if RENDER_WRAPPER is not None:
        html = RENDER_WRAPPER(html)
    **if jupyter or is_in_jupyter():  # return HTML rendered by IPython display()**
        from IPython.core.display import display, HTML

        return display(HTML(html))
    return html
```
The is_in_jupyter() property is set to true if the code is in a jupyter notebook. But in this case, I still want to export it as an html along with displaying in the notebook. 
I'm able to have a workaround by changing the above line of code to :
```
**if (jupyter or is_in_jupyter()) and not page:**
```
There maybe other cases where it may break due to it. Need to resolve this in the correct manner.

**Comment by ines** [comment]
Are you using the latest version of spaCy? I'm pretty sure this was fixed recently.

**Comment by mansiganatra** [comment]
I was using version 2.1.3 . I updated to version 2.1.4, but the issue still persists. My use-case is as follows:
I want to display the html render in current jupyter notebook, as well as export the same markup to .html file for later use. My code looks like this:

 displacy.render(document, style='ent', jupyter=True)   
 html =  displacy.render(document, style='ent', page=True)
 write_to_html_file(html_filepath, html)

which gives me an error of TypeError: write() argument must be str, not None because the line displacy.render(document, style='ent', page=True) returns None.

I still need to change the following piece of code:

**if jupyter or (jupyter is None and is_in_jupyter()):**
        # return HTML rendered by IPython display()
        from IPython.core.display import display, HTML

        return display(HTML(html))
to:
**if jupyter or (jupyter is None and is_in_jupyter() and not page):**
        # return HTML rendered by IPython display()
        from IPython.core.display import display, HTML

        return display(HTML(html))

Not sure this is the best way to do it, but solves my issue for now.  I guess there will be reasonable use cases where we need to do both from a jupyter notebook- show the render in current notebook and save the html page for alter use?

**Comment by ines** [comment]
Can you just set `jupyter=False` explicitly? This is the part that decides that the output should be wrapped with IPython's `display()` and rendered in the notebook, instead of just returning the HTML markup. If you disable that, you should get the a raw string containing the HTML.

**Comment by mansiganatra** [comment]
Works for now. But it may not be the best way to do it as it now makes ```page=True```  attribute redundant? Updating the documentation might help I guess if this is the intended use of the API.

**Comment by ines** [comment]
It shouldn't really make the `page=True` redundant, though? Unless I misunderstand the comment. If you set `page=True`, the markup will be wrapped as a full valid HTML page with `<html>` etc. If you set `page=False`, you'll just get the markup of whatever you're currently rendering (the SVG, the text with entities etc.). So depending on what you need, you can get the respective markup.

**Comment by mansiganatra** [comment]
Yeah my bad. Works fine. Maybe the documentation can add the ```jupyter=False``` use for this use case.
Closing the issue.
