### ISSUE TITLE
KeyError when adding special tokens

### ISSUE THREAD

**Issue by fmfn** [explosion/spaCy#624]
I am trying to run the example of adding special tokens to the tokenizer and getting the following keyerror:

```KeyError                                  Traceback (most recent call last)
<ipython-input-3-3c4362d5406f> in <module>()
      8             POS: u'VERB'},
      9         {
---> 10             ORTH: u'me'}])
     11 assert [w.text for w in nlp(u'gimme that')] == [u'gim', u'me', u'that']
     12 assert [w.lemma_ for w in nlp(u'gimme that')] == [u'give', u'-PRON-', u'that']

/Users/<user>/venvs/general/lib/python3.5/site-packages/spacy/tokenizer.pyx in spacy.tokenizer.Tokenizer.add_special_case (spacy/tokenizer.cpp:8460)()

/Users/<user>/venvs/general/lib/python3.5/site-packages/spacy/vocab.pyx in spacy.vocab.Vocab.make_fused_token (spacy/vocab.cpp:7879)()

KeyError: 'F'
```

The code used is the following:

```
import spacy
from spacy.attrs import ORTH, POS, LEMMA

nlp = spacy.load("en", parser=False)

assert [w.text for w in nlp(u'gimme that')] == [u'gimme', u'that']
nlp.tokenizer.add_special_case(u'gimme',
    [
        {
            ORTH: u'gim',
            LEMMA: u'give',
            POS: u'VERB'},
        {
            ORTH: u'me'}])
assert [w.text for w in nlp(u'gimme that')] == [u'gim', u'me', u'that']
assert [w.lemma_ for w in nlp(u'gimme that')] == [u'give', u'-PRON-', u'that']
```

Am I missing something here?

System info:
- MacOS
- python3.5.2
- spacy 1.2.0

**Comment by honnibal** [comment]
Sorry about this — the docs got a bit ahead of the code here. The docs describe how the feature *should* work, and will work shortly (I'll probably fix it over the weekend).

At the moment you can use the key `"F"` instead of `ORTH`, `"L"` instead of `LEMMA`, and `"pos"` instead of `POS`.

**Comment by fmfn** [comment]
Nice!

I got it to work by passing 'F' and working backwards, after I traced the `make_fused_token` method. But "L" and "P" were extra hidden.

Thanks for the lightning reply and superb work.

**Comment by fmfn** [comment]
After changing it to:
```
nlp.tokenizer.add_special_case(
    u'gimme',
    [
        {
            "F": u'gim',
            "L": u'give',
            "pos": u'VERB'
        },
        {
            "F": u'me',
        }
    ]
)
```

I get:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-6-df7b9eb25a34> in <module>()
      8         },
      9         {
---> 10             "F": u'me',
     11         }
     12     ]

/Users/<>/venvs/general/lib/python3.5/site-packages/spacy/tokenizer.pyx in spacy.tokenizer.Tokenizer.add_special_case (spacy/tokenizer.cpp:8460)()

/Users/<>/venvs/general/lib/python3.5/site-packages/spacy/vocab.pyx in spacy.vocab.Vocab.make_fused_token (spacy/vocab.cpp:7907)()

/Users/<>/venvs/general/lib/python3.5/site-packages/spacy/morphology.pyx in spacy.morphology.Morphology.assign_tag (spacy/morphology.cpp:3919)()

KeyError: 97
```

**Comment by honnibal** [comment]
This should now be fixed on master. Thanks for your patience.

**Comment by robbymeals** [comment]
I'm still seeing this same issue on conda installed v1.6.0. Tried installing from source, didn't fix.
```rmealey-03:spaCy robert.mealey$ pip install -e .
Obtaining file:///Users/robert.mealey/spaCy
Requirement already satisfied: numpy>=1.7 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: murmurhash<0.27,>=0.26 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: cymem<1.32,>=1.30 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: thinc<6.6.0,>=6.5.0 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: plac<0.9.3 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: six in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: pathlib in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: sputnik<0.10.0,>=0.9.2 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: ujson>=1.35 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: dill<0.3,>=0.2 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from spacy==1.6.0)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy==1.6.0)
Requirement already satisfied: wrapt in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy==1.6.0)
Requirement already satisfied: cytoolz<0.9,>=0.8 in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from thinc<6.6.0,>=6.5.0->spacy==1.6.0)
Requirement already satisfied: semver in /Users/robert.mealey/anaconda3/lib/python3.6/site-packages (from sputnik<0.10.0,>=0.9.2->spacy==1.6.0)
Installing collected packages: spacy
  Found existing installation: spacy 1.6.0
    Uninstalling spacy-1.6.0:
      Successfully uninstalled spacy-1.6.0
  Running setup.py develop for spacy
Successfully installed spacy
rmealey-03:spaCy robert.mealey$ ipython
Python 3.6.0 |Anaconda 4.3.0 (x86_64)| (default, Dec 23 2016, 13:19:00)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import spacy

In [2]: nlp = spacy.load("en")

In [3]: nlp.tokenizer.add_special_case(u'part-time', [{"F":u'part-time', "L":u'part-time', "pos":u"ADJ"}])
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-38ad7ade1d37> in <module>()
----> 1 nlp.tokenizer.add_special_case(u'part-time', [{"F":u'part-time', "L":u'part-time', "pos":u"ADJ"}])

/Users/robert.mealey/spaCy/spacy/tokenizer.pyx in spacy.tokenizer.Tokenizer.add_special_case (spacy/tokenizer.cpp:8678)()
    387         cached.length = len(substrings)
    388         cached.is_lex = False
--> 389         cached.data.tokens = self.vocab.make_fused_token(substrings)
    390         key = hash_string(string)
    391         self._specials.set(key, cached)

/Users/robert.mealey/spaCy/spacy/vocab.pyx in spacy.vocab.Vocab.make_fused_token (spacy/vocab.cpp:8348)()
    347             token.lex = <LexemeC*>self.get_by_orth(self.mem, props[attrs.ORTH])
    348             if attrs.TAG in props:
--> 349                 self.morphology.assign_tag(token, props[attrs.TAG])
    350             for attr_id, value in props.items():
    351                 Token.set_struct_attr(token, attr_id, value)

/Users/robert.mealey/spaCy/spacy/morphology.pyx in spacy.morphology.Morphology.assign_tag (spacy/morphology.cpp:4508)()
     66             tag_id = self.reverse_index[self.strings[tag]]
     67         else:
---> 68             tag_id = self.reverse_index[tag]
     69         self.assign_tag_id(token, tag_id)
     70

KeyError: 82

In [4]:```

**Comment by robbymeals** [comment]
Oh, nvm, the code actually works as documented now after upgrade. Sorry about that.
