### ISSUE TITLE
TextCategorizer doesn't work with Transformers

### ISSUE THREAD

**Issue by lbenc135** [explosion/spaCy#6701]
## How to reproduce the behaviour
Here's a sample code to reproduce the issue: https://pastebin.com/TzrLwPAN

It seems like the `initialize` method tries to assert that the transformer's output is of the same type as gold label, instead of the textcat's output. Am I misunderstanding something?

## Output

```
Traceback (most recent call last):
  File "/home/livio/.config/JetBrains/PyCharmCE2020.3/scratches/spacy_test.py", line 55, in <module>
    nlp.initialize(lambda: iter([example]))  # <-- Breaks here
...
    self.init(self, X=X, Y=Y)
  File "/home/livio/Work/platform/venv/lib/python3.8/site-packages/thinc/layers/chain.py", line 86, in init
    layer.initialize(X=curr_input, Y=Y)
  File "/home/livio/Work/platform/venv/lib/python3.8/site-packages/thinc/model.py", line 294, in initialize
    validate_fwd_input_output(self.name, self._func, X, Y)
  File "/home/livio/Work/platform/venv/lib/python3.8/site-packages/thinc/util.py", line 424, in validate_fwd_input_output
    raise DataValidationError(name, X, Y, e.errors()) from None
thinc.util.DataValidationError: 

Data validation error in 'para-attn'
X: <class 'thinc.types.Ragged'> Y: <class 'numpy.ndarray'>

Y -> 0   instance of Ragged, tuple or dict expected
```
or
```
Data validation error in 'transformer'
X: <class 'list'> Y: <class 'numpy.ndarray'>
Y -> 0   instance of FullTransformerBatch, tuple or dict expected
```

## Info about spaCy

- **spaCy version:** 3.0.0rc3
- **Platform:** Linux-5.8.0-33-generic-x86_64-with-glibc2.32 (Ubuntu)
- **Python version:** 3.8.6

**Comment by svlandeg** [comment]
Hi! We've encountered this error before, it should be fixed by https://github.com/explosion/spaCy/pull/6431 (this is already merged) and https://github.com/explosion/spacy-transformers/pull/231 (which will be merged once `3.0.0rc3` is published).

I'll tentavily close this and merge it with https://github.com/explosion/spaCy/issues/6401. Once `3.0.0rc3` is officially published, we hope this will be fully resolved. If not, please do let us know!

**Comment by lbenc135** [comment]
Hey @svlandeg I forgot to mention, I pulled the newest code from the `develop` branch (including that PR), installed from source, and I'm still having the same problem.

**Comment by svlandeg** [comment]
I think that's to be expected, because https://github.com/explosion/spacy-transformers/pull/231 hasn't been merged yet. 

Internally, we're working on publishing `3.0.0rc3`, after which we can refer to it from `spacy-transformers`, run the CI properly and merge that PR, then also release an updated version of `spacy-transformers`. Because of the dependencies, it's a little complex. You could try pulling the code from https://github.com/explosion/spacy-transformers/pull/231 and make sure to also have the latest code from Thinc including https://github.com/explosion/thinc/pull/431, or just wait a bit until we publish all updated release candidates ;-)
