### ISSUE TITLE
Download of 1.6 en model fails with ssl exception

### ISSUE THREAD

**Issue by tmbo** [explosion/spaCy#920]
When trying to download the en model with spacy 1.6(using `python -m spacy.en.download all`) the download fails with:

```
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

**Comment by ines** [comment]
Damn, looks like the SSL certificate might have expired!

In the meantime, you can always download the models manually from the [v1.6 release on GitHub](https://github.com/explosion/spaCy/releases/tag/v1.6.0) (just drop the data directory into `spacy/data`). Our download server will soon be rerouted to download these files as well.

**Comment by honnibal** [comment]
Fixed the certificate -- sorry for the delay.

**Comment by sankethpb** [comment]
We still get this error and are unable to install models using python -m spacy.en.download all
Spacy version - 1.7.2
Could you please help here?

**Comment by ines** [comment]
@sankethpb The `spacy.en.download all` command is deprecated in v1.7+. You can now download the default English model with `python -m spacy download en`.

For more info on the available models and new download commands, see the [models documentation](https://spacy.io/docs/usage/models).

**Comment by sankethpb** [comment]
I used the new command `python -m spacy download en` with  Spacy V1.7.2
I still get [SSL: CERTIFICATE_VERIFY_FAILED]  error on both Windows 10 / Ubuntu 16.04 LTS

**Comment by ines** [comment]
@sankethpb Hm, this is very strange –  the downloader gets the model URLs [from our models repo on GitHub](https://github.com/explosion/spacy-models) (via SSL, but GitHub's certificate should be fine), and then uses pip to install them.

Do you get the same error if you run this manually?

```bash
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
```

If it still doesn't work, you can always just download the model archive manually via the browser and then point pip to the archive on your local file system. To load the model, you'll have to set up a [shortcut link](https://spacy.io/docs/usage/cli#link) manually, or simply import the model as a module and call its `load()` method:

```python
import en_core_web_sm
nlp = en_core_web_sm.load()
```

**Comment by sankethpb** [comment]
I also tried to using pip install `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz` and still get the same SSL Verification failed error.

The short links didn't work for me (or maybe I did it wrong) since I use Spacy with RASA Nlu, finally I modified pip's download.py to ignore SSL verification and now it installed successfully. It's a bad workaround though.

It would be great if it can be fixed.
Thanks in advance.

**Comment by honnibal** [comment]
Well, the service is GitHub, and the software that's installing it is pip --- so I think it's almost certain that the problem is in your system.

I think some Python versions were linked against an old version of OpenSSL, which didn't implement some SSL protocol correctly. I don't remember the details entirely. But I think if you update your Python and possibly your OpenSSL, it'll work correctly.

**Comment by AdeMiller** [comment]
I'm still seeing this issue. The following workaround fixed it from me
```
pip install  http://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz --user --trusted-host github-production-release-asset-2e65be.s3.amazonaws.com -v
```
You may have to change the trusted host depending on what and were you are downloading. The `-v` option will show the exact URL and hostname that requires a trust.
